name: 'Plugin Deploy'
description: 'Deploy to the WordPress Plugin Repository'
author: 'SargasInc'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  generate-zip:
    description: 'Generate package zip file?'
    default: false
outputs:
  zip-path:
    description: 'Path to zip file'
    value: ${{ steps.deploy.outputs.zip-path }}
runs:
  using: 'composite'
  steps:
    - id: deploy
      env:
        INPUT_GENERATE_ZIP: ${{ inputs.generate-zip }}
      run: ${{ github.action_path }}/script.sh
      shell: bash